// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SAN_Imp_SkipParallelEventPreload","status":true,"description":"並列イベントプリロードスキップ 1.0.0\r\nパフォーマンス改善プラグインです。","parameters":{}}
];
